p8105_hw1_jl7033
================
Joe LaRocca
2024-09-19

## Problem 1

``` r
data("penguins", package = "palmerpenguins")

penguins
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ##  1 Adelie  Torgersen           39.1          18.7               181        3750
    ##  2 Adelie  Torgersen           39.5          17.4               186        3800
    ##  3 Adelie  Torgersen           40.3          18                 195        3250
    ##  4 Adelie  Torgersen           NA            NA                  NA          NA
    ##  5 Adelie  Torgersen           36.7          19.3               193        3450
    ##  6 Adelie  Torgersen           39.3          20.6               190        3650
    ##  7 Adelie  Torgersen           38.9          17.8               181        3625
    ##  8 Adelie  Torgersen           39.2          19.6               195        4675
    ##  9 Adelie  Torgersen           34.1          18.1               193        3475
    ## 10 Adelie  Torgersen           42            20.2               190        4250
    ## # ℹ 334 more rows
    ## # ℹ 2 more variables: sex <fct>, year <int>

The data include the species of penguin, the island the penguin comes
from, the penguins’ bill length, bill depth, and flipper length (all
measured in mm), their body mass (measured in g), their sex (male or
female) and the year in which the data point was taken (from 2007 to
2009, inclusive).

The dataset has 344 rows, meaning that there are 344 penguins in the
dataset. It has 8 columns, so there are a total of 8 variables being
measured.

The mean flipper length is about 200.92 mm, not including penguins for
which the flipper length value is missing.

``` r
flipper_bill_plot = ggplot(data = penguins, 
       aes(x = bill_length_mm, 
           y = flipper_length_mm,
           col = species)) + 
  geom_point() + 
  labs(title = "Plot of Flipper Length vs. Bill Length",
       x = "Bill Length (mm)",
       y = "Flipper Length (mm)")

flipper_bill_plot
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_jl7033_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
ggsave(filename = "flipper_bill_plot.png",
  plot = flipper_bill_plot)
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

## Problem 2

``` r
problem_2_df = tibble(
  random_normal = rnorm(10, mean = 0, sd = 1),
  logical = random_normal > 0,
  character = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  factor = factor(
    c("High", "Medium", "Low", "Low", "Medium", 
      "Medium", "High", "Low", "High", "Low"))
)

problem_2_df
```

    ## # A tibble: 10 × 4
    ##    random_normal logical character factor
    ##            <dbl> <lgl>   <chr>     <fct> 
    ##  1        1.18   TRUE    a         High  
    ##  2        1.80   TRUE    b         Medium
    ##  3        0.291  TRUE    c         Low   
    ##  4       -0.335  FALSE   d         Low   
    ##  5        0.198  TRUE    e         Medium
    ##  6        0.475  TRUE    f         Medium
    ##  7        0.484  TRUE    g         High  
    ##  8        0.677  TRUE    h         Low   
    ##  9       -1.67   FALSE   i         High  
    ## 10        0.0566 TRUE    j         Low

##### Take the mean of the standard Normal and Logical column

``` r
problem_2_df %>% 
  pull(random_normal) %>% 
  mean()
```

    ## [1] 0.315678

``` r
problem_2_df %>% 
  pull(logical) %>% 
  mean()
```

    ## [1] 0.8

The means of the `random_normal` and `logical` columns are 0.315678 and
0.8 respectively. The `character` and `factor` columns have no defined
mean; when I try to take their mean, I get an error message saying that
the argument is not numeric or logical.

##### Try converting variables using as.numeric()

``` r
problem_2_df %>% 
  mutate(logical = as.numeric(logical)) %>% 
  mutate(character = as.numeric(character)) %>% 
  mutate(factor = as.numeric(factor))
```
